### ISSUE TITLE
Арукоген генерит не торт

### ISSUE THREAD

**Issue by artem30801** [bart02/DroneSwarm#2]
Пример правильной карты:
[
    1, 2, 3, 28, 29, 30,
    4, 5, 6, 31, 32, 33,
    7, 8, 9, 34, 35, 36,
    10, 11, 12, 37, 38, 39,
    13, 14, 15, 40, 41, 42,
    16, 17, 18, 43, 44, 45,
    19, 20, 21, 46, 47, 48,
    22, 23, 24, 49, 50, 51,
    25, 26, 27, 52, 53, 54
    ]
Так же нужен вывод текстовых запросов пользователю

**Comment by bart02** [comment]
https://github.com/bart02/DroneSwarm/commit/0b4f46e2d6c8c588d520177786bf687a235d04fd
Теперь работает
